web-config:
  max_total_connections: 1000
  max_per_route_connections: 1000
  connect_timeout: 1000
  read_timeout: 5000

management:
  info:
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"